---
- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: nexus
  register: nexus_temp_dir
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Interpolate Ansible variables
  template:
    src: docker-compose.yml.j2
    dest: "{{ nexus_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Deploy nexus in Swarm
  command: 'docker stack deploy --compose-file {{ nexus_temp_dir.path }}/docker-compose.yml nexus'
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

# - name: Record Traefik DNS
#   ara_record:
#     key: "nexus_host"
#     value: "http://{{ nexus_host }}"
#     type: url
#   tags:
#     - skip_ansible_lint